# Generated by Django 4.2.5 on 2023-09-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(help_text='Enter a tag for yur post', max_length=25, null=True),
        ),
    ]
