# Generated by Django 4.2.5 on 2023-09-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0002_remove_post_tags_delete_tag_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed_user_id',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following_user_id',
            new_name='follower',
        ),
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='subscription status of users', max_length=8),
        ),
    ]
