# Generated by Django 4.2.5 on 2023-09-30 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0005_post_likes_delete_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(choices=[(1, '👍'), (2, '👎'), (3, '💖')], related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
