# Generated by Django 4.2.5 on 2023-10-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0007_remove_post_likes_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='type_of_reaction',
            field=models.CharField(choices=[('like', '👍'), ('dislike', '👎')], help_text='Reaction for the post', max_length=10),
        ),
    ]
