# Generated by Django 4.2.5 on 2023-10-10 18:38

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0008_alter_reaction_type_of_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image_file')),
            ],
        ),
        migrations.RemoveField(
            model_name='follow',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media_file',
        ),
        migrations.AddField(
            model_name='post',
            name='title_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='title_image'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='media',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangogramm.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ManyToManyField(blank=True, related_name='media_files', to='djangogramm.media'),
        ),
    ]
