# Generated by Django 4.2.5 on 2023-10-10 18:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0009_media_remove_follow_status_remove_post_media_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='avatar'),
        ),
    ]
