# Generated by Django 4.2.5 on 2023-10-10 20:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='post_image'),
        ),
    ]
